modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="cdgbiodiesel"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets"
authors="bloodclover"
description='''
An addon for Create Diesel Generators that adds more ways to produce biodiesel.
'''

[[dependencies.cdgbiodiesel]] 
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.cdgbiodiesel]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.cdgbiodiesel]]
modId="create"
type="required"
versionRange="${create_version}"
ordering="NONE"
side="BOTH"

[[dependencies.cdgbiodiesel]]
modId="createdieselgenerators"
type="required"
versionRange="${cdg_version}"
ordering="NONE"
side="BOTH"
